### ISSUE TITLE
[Question] Why PerAct couldn't solve "Push Buttons" (compares to HiveFormer)?

### ISSUE THREAD

**Issue by berniewang8177** [peract/peract#14]
Dear author,

Thank you for sharing your awesome work!

In the readme, you mention that 
" Impossible tasks: Some tasks like push_buttons are not solvable by PerAct since it doesn't have any memory."
Is it because the PerAct's policy is P(a_t | O_t, Instruction) ? Since history observation is not provided, there's no way for PerAct to keep track of its progress for Instruction following ?

Best,

**Comment by MohitShridhar** [comment]
@berniewang8177, yes. If the task is "press the red button, then the blue button, and then the green button", the agent won't know which button was pressed previously, and will have to guess which part of the sequence it's at.
