### ISSUE TITLE
About training multi-task. 

### ISSUE THREAD

**Issue by maineJiang** [peract/peract#25]
Hi, thank again for your great work. It really helps a lot. 

Now I have successfully used Peract to do some tasks in real world which is very exiciting. May I ask a question about train multi-task model. I modified the peract_colab code to train the single task model. Now I want to extend it to support multi-task training. As far as I am concerned, the model only distinguish between different tasks by language prompt. So is it ok to simply consider all tasks to be a mixed huge task and train them? I mean simply put all data together and set longer traning iterations. Will I meet anything unexpected if I have different demo numbers for different tasks?

**Comment by MohitShridhar** [comment]
@maineJiang, nice!

Yes, you can consider multiple tasks as one large task. But in this repo, I make sure each batch includes an equal distribution of task categories to avoid over-sampling some tasks. And yes, you have to train the agent for more iterations.

For different number of demos, I just use a min function. So `min(num_of_demos_wanted, number_of_demos_in_the_dataset)`. This should work with uneven dataset sizes.

**Comment by maineJiang** [comment]
Got it，thank you very much！

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: Mohit Shridhar ***@***.***>
发送时间: Friday, June 16, 2023 11:27:52 PM
收件人: peract/peract ***@***.***>
抄送: Wenyi Jiang ***@***.***>; Mention ***@***.***>
主题: Re: [peract/peract] About training multi-task. (Issue #25)


@maineJiang<https://github.com/maineJiang>, nice!

Yes, you can consider multiple tasks as one large task. But in this repo, I make sure each batch includes an equal distribution of task categories to avoid over-sampling some tasks. And yes, you have to train the agent for more iterations.

For different number of demos, I just use a min function. So min(num_of_demos_wanted, number_of_demos_in_the_dataset). This should work with uneven dataset sizes.

―
