### ISSUE TITLE
Question regarding inference

### ISSUE THREAD

**Issue by sriharshakoribille** [peract/peract#28]
Hello Mohit,

I'm trying to run PERACT in pybullet with similar environments as RLBench for manipulation. I have few questions regarding this:

1) I'm confused as to how to set the `episode_length` parameter during training. In your repo, all the RLBench episodes were atleast 100+ timesteps and in your colab notebook, the `episode_length` parameter was configured as 10 and in your code, it was 25. How should this be decided?

2) During inference, what should the `time_step` input be that should be given with the input observation. Suppose the training of the task had 100 timesteps and 4 key points at every 25th timestep. Now if we want to run PERACT during inference on this task, how should we give the time_steps for the observations? Since PERACT predicts the keypoint poses, should our input time_steps be 0,1,2,3 or 0,25,50,75?

Can you please elaborate on this.

Thank you

**Comment by sriharshakoribille** [comment]
Hi Mohit, yeah it is related to the same issue. So essentially, the time steps during inference should then be 0,1,2,..
Thank you for the clarifications! I'll try them out.

Also I have another question, the franka panda arm renders in complete black color in pybullet instead of its usual white color and texture (picture attached) . This is an issue with the pybullet.  All my training and inference data would be having this black colored arm. Do you think this will impact the performance of peract?

![voxel_grid](https://github.com/peract/peract/assets/3256247/392ca790-6923-48eb-91a2-3bb6ab445b03)

**Comment by MohitShridhar** [comment]
I don't think it matters at all. As long as it's consistently the same color across train and test.

**Comment by sriharshakoribille** [comment]
Great! Thank you for the clarifications Mohit!
