### ISSUE TITLE
RLBench Task Modifications

### ISSUE THREAD

**Issue by PietroVitiello** [peract/peract#29]
Hi, I noticed from the paper that you have modified some of the tasks to include variations. Would you be able to share these with us please?
Thank you!

**Comment by MohitShridhar** [comment]
@PietroVitiello, this repo uses my fork of RLBench: https://github.com/MohitShridhar/RLBench/tree/peract

The changes are described in Appendix A in the paper.

**Comment by PietroVitiello** [comment]
Thank you very much for the prompt reply! I confirm I see the additional tasks on your fork.
