### ISSUE TITLE
The `low_dim_state` in RLBench.

### ISSUE THREAD

**Issue by AoqunJin** [peract/peract#31]
I found that `low_dim_state` is used in PerAct. How much impact will this have on the experimental results?

In `peract/agents/peract_bc/launch_utils.py`

QAttentionPerActBCAgent `include_low_dim_state=True`.

**Comment by MohitShridhar** [comment]
@AoqunJin, the `gripper_open` state and `time_left` are probably important for the agent to figure out which part of the trajectory it's at, e.g., since the gripper is closed, the object has probably been grasped. But I don't think I ran ablations. It might be good to investigate this.

**Comment by AoqunJin** [comment]
Thanks for your patient reply, I will try to test them in my experiments and ablation experiments, based on PerAct. 😊😊😊

**Comment by AoqunJin** [comment]
![lineplot](https://github.com/peract/peract/assets/97787941/e7fccf71-ce7c-436a-973d-bbdbcff9ff3d)
