### ISSUE TITLE
Questions about description

### ISSUE THREAD

**Issue by SatireY** [peract/peract#36]
I noticed that the fill_replay function in your code always selects the first description.
```
desc = descs[0]
```
But an RLBench task usually has several different descriptions.
Can the trained model generalize to other descriptions?

**Comment by MohitShridhar** [comment]
@SatireY, I made this design choice to make it easier for PerAct to learn. But in theory, randomly sampling from all descriptions should work. CLIP's language encoder might be robust to small paraphrases, but I haven't tested this extensively.

**Comment by SatireY** [comment]
Ok, I see. Thank you for your reply
