### ISSUE TITLE
About checkpoint parameter

### ISSUE THREAD

**Issue by TengBoYuu** [peract/peract#48]
Hi，thank you for your great work☺️
I download the checkpoint with 2048 latents，but I notice the shape of the parameter ‘_qnet.module.pos_encoding‘ is `torch.Size([1, 20, 20, 20, 128])`，which means `pos_encoding_with_lang = False`，did I misunderstand or there was no language condition for position encoding during training the checkpoint ?
![CleanShot 2024-07-30 at 20 36 34](https://github.com/user-attachments/assets/32a1510a-b218-4a11-b9cc-b5d8c9a880f6)

**Comment by MohitShridhar** [comment]
@TengBoYuu, there is [language conditioning](https://github.com/peract/peract/blob/main/agents/peract_bc/perceiver_lang_io.py#L378), but there is no positional embeddings for those lang tokens. So "put the marker in the drawer" is treated as a bag of words.

**Comment by TengBoYuu** [comment]
Okay, thank you. I see what you mean.
