### ISSUE TITLE
My Voxel haven't  RGB value

### ISSUE THREAD

**Issue by hahans** [peract/peract#51]
I followed your VoxelGrid() function, and  use point cloud and RGB images ,when I put those into function VoxelGrid ,I got a vector ,which shape was (1,10,100,100,100)(I set batch size = 1),its value always was 0.0. After that ,when I use visualise_voxel() function and it only show the scene with white boxes.

![Screenshot from 2024-09-10 16-58-53](https://github.com/user-attachments/assets/6d50984d-4759-4540-a494-320ba604ccf3)

**Comment by MohitShridhar** [comment]
@hahans did you follow this [notebook](https://colab.research.google.com/drive/1HAqemP4cE81SQ6QO1-N85j5bF4C0qLs0?usp=sharing)?

Looks like the RGB values aren't scaled properly (like 255 -> 1.0) or the indices are wrong. Try to follow the colab notebook, and see if there are any differences in your implementation.

**Comment by hahans** [comment]
> @hahans did you follow this [notebook](https://colab.research.google.com/drive/1HAqemP4cE81SQ6QO1-N85j5bF4C0qLs0?usp=sharing)?
> 
> Looks like the RGB values aren't scaled properly (like 255 -> 1.0) or the indices are wrong. Try to follow the colab notebook, and see if there are any differences in your implementation.

Thanks ! It helps me a lot.
