### ISSUE TITLE
problem with  nvidia-xconfig  

### ISSUE THREAD

**Issue by rebecajohn** [peract/peract#53]
Command : sudo nvidia-xconfig -a --use-display-device=None --virtual=1280x1024

output : sudo: nvidia-xconfig: command not found

**Comment by MohitShridhar** [comment]
@rebecajohn, this issue is specific to your setup. Please google these issues: https://ubuntuforums.org/showthread.php?t=1756211

**Comment by rebecajohn** [comment]
hi, after folowing the commands in that , the following error occurred -> E: Package 'nvidia-current' has no installation candidate
